# Seahawks vs Rams — Player Prop Analysis

This notebook documents my second iteration of a structured player prop tracking model.
The goal is to improve thesis validation, postgame review, and accuracy tracking
based on lessons learned from my Bears vs Rams project.

All baseline entries are frozen prior to kickoff.

## Objectives

- Track baseline player props with timestamps
- Log market movement and thesis alignment
- Validate pregame reasoning vs postgame outcomes
- Identify when correct logic still leads to incorrect results
- Improve future prop modeling accuracy

## Methodology

This notebook separates the analysis into three structured phases, building on lessons learned from prior projects:

1. **Baseline assumptions** – capture player prop lines and probabilities before any market movement. These reflect initial expectations grounded in matchup, player usage, and historical trends.
2. **Pregame adjustments** – track updated market trends, shifts in value, and thesis support. Adjustments incorporate new information such as injuries, team strategy, or emerging tendencies.
3. **Postgame outcomes** – record final stats, compare actual performance against baseline and adjusted expectations, validate the thesis, and document key observations.

**Note:** Baseline entries are frozen once the pregame snapshot is captured to maintain process integrity and prevent hindsight bias.

**Project Reflection:** This version builds on the Bears vs Rams analysis by emphasizing structured reasoning, clearer adjustment tracking, and enhanced postgame reflection — demonstrating iterative improvement in predictive rigor and notebook organization.

## Pregame Context

- Seahawks entered as early favorites, shaping conservative late-game scripts
- Rams projected to trail, increasing pass-rate and RB receiving opportunities
- Defensive shell tendencies and coverage allocation were central to prop selection


Pregame Model Notes

Some props in this slate favored players on teams projected to lose.
Historically, player props on losing teams hit at a lower rate due to
script changes and volume uncertainty.

This project tracks whether strong matchup-based reasoning can still
produce correct results despite adverse game scripts.

## Evolution From Prior Project

Compared to the Bears vs Rams notebook, this analysis:
- Separates *Result* from *Thesis Validation* to avoid hindsight bias
- Emphasizes game script and efficiency over raw volume
- Focuses on outcome interpretation rather than re-explaining mechanics

This reflects a shift from learning the framework to refining it.

In [110]:
# Step 1: Imports & DataFrame Initialization

import pandas as pd
from datetime import datetime

# Define all columns including placeholders for postgame data
columns = [
    "Player",
    "Prop",
    "Type",
    "Pregame Hypothesis",
    "Confidence",
    "Market Alignment / Notes",
    "Baseline Prop",
    "Baseline Timestamp",
    "Current Prop",
    "Current Timestamp",
    "Adjusted Value",
    "Pregame Thesis Status",
    "Final Stat",
    "Result",
    "Thesis Validation",
    "Postgame Notes"
]

# Create empty DataFrame
df = pd.DataFrame(columns=columns)
df

Empty DataFrame
Columns: [Player, Prop, Type, Pregame Hypothesis, Confidence, Market Alignment / Notes, Baseline Prop, Baseline Timestamp, Current Prop, Current Timestamp, Adjusted Value, Pregame Thesis Status, Final Stat, Result, Thesis Validation, Postgame Notes]
Index: []

In [111]:
# Step 2: Pre-game prop entries

data = [
    {
        "Player": "Barner",
        "Prop": "Receiving Yards",
        "Type": "OVER",
        "Pregame Hypothesis": "Barner exceeds with playaction passing where Rams allow tight ends to hit explosive yards.",
        "Confidence": "~66%",
        "Market Alignment / Notes": "Market underestimates slot usage; early-week data supports OVER",
        "Baseline Prop": "OVER 28.5",
        "Baseline Timestamp": "2026-01-23 02:20",
        "Current Prop": "OVER 30 (improved value)",
        "Current Timestamp": "2026-01-24 AM",
        "Adjusted Value": "More favorable to OVER 30",
        "Pregame Thesis Status": "Supported by market",
        "Final Stat": 13,
        "Result": "UNDER",
        "Thesis Validation": "Invalidated",
        "Postgame Notes": "Ball was spread evenly, given short routes, not game focus."
    },
    {
        "Player": "Walker",
        "Prop": "Rushing Yards",
        "Type": "UNDER",
        "Pregame Hypothesis": "Rams will collapse the pocket and apply extra measures to contain him; Seahawks won’t establish their run game due to game script and Charbonnet injury.",
        "Confidence": "~61%",
        "Market Alignment / Notes": "Market may overvalue workload; Rams rush D strong",
        "Baseline Prop": "UNDER 85.5",
        "Baseline Timestamp": "2026-01-23 02:22",
        "Current Prop": "UNDER 85.5",
        "Current Timestamp": "2026-01-24 AM",
        "Adjusted Value": "Trend supports UNDER due to game script",
        "Pregame Thesis Status": "Strongly supported by thesis",
        "Final Stat": 62,
        "Result": "UNDER",
        "Thesis Validation": "Validated",
        "Postgame Notes": "Walker was contained, 19 carries for 3.3 ypc; game script had Seahawks leading, limiting effectiveness."
    },
    {
        "Player": "Parkinson",
        "Prop": "Receptions",
        "Type": "OVER",
        "Pregame Hypothesis": "Stafford trusts Parkinson as his 2nd read; Davante Adams draws coverage, giving Parkinson volume and influence in the game.",
        "Confidence": "~68%",
        "Market Alignment / Notes": "Market line reasonable, slight edge for OVER",
        "Baseline Prop": "OVER 2.5",
        "Baseline Timestamp": "2026-01-23 02:25",
        "Current Prop": "OVER 3",
        "Current Timestamp": "2026-01-24 AM",
        "Adjusted Value": "Volume will increase due to coverage",
        "Pregame Thesis Status": "Supported by matchup + Stafford trust",
        "Final Stat": 3,
        "Result": "OVER",
        "Thesis Validation": "Validated",
        "Postgame Notes": "Achieved line and produced efficiency over volume."
    },
    {
        "Player": "Blake Corum",
        "Prop": "Receiving Yards",
        "Type": "OVER",
        "Pregame Hypothesis": "Seahawks allow RB receiving yards with their shell defense; Corum should exploit checkdowns and screens, complementing Parkinson’s receptions.",
        "Confidence": "~57%",
        "Market Alignment / Notes": "Market underestimates RB receiving usage; volatility remains",
        "Baseline Prop": "OVER 0.5",
        "Baseline Timestamp": "2026-01-23 02:28",
        "Current Prop": "OVER 1",
        "Current Timestamp": "2026-01-24 AM",
        "Adjusted Value": "Favorable for over 0.5; high variance remains",
        "Pregame Thesis Status": "Supported by scheme and RB usage",
        "Final Stat": 3,
        "Result": "OVER",
        "Thesis Validation": "Validated",
        "Postgame Notes": "Capitalized on defensive shell; linebacker/corners dropped back as expected, beating line."
    }
]

# Insert into DataFrame
df = pd.DataFrame(data)
df

,Player,Prop,Type,Pregame Hypothesis,Confidence,Market Alignment / Notes,Baseline Prop,Baseline Timestamp,Current Prop,Current Timestamp,Adjusted Value,Pregame Thesis Status,Final Stat,Result,Thesis Validation,Postgame Notes
0,Barner,Receiving Yards,OVER,Barner exceeds with playaction passing where R...,~66%,Market underestimates slot usage; early-week d...,OVER 28.5,2026-01-23 02:20,OVER 30 (improved value),2026-01-24 AM,More favorable to OVER 30,Supported by market,13,UNDER,Invalidated,"Ball was spread evenly, given short routes, no..."
1,Walker,Rushing Yards,UNDER,Rams will collapse the pocket and apply extra ...,~61%,Market may overvalue workload; Rams rush D strong,UNDER 85.5,2026-01-23 02:22,UNDER 85.5,2026-01-24 AM,Trend supports UNDER due to game script,Strongly supported by thesis,62,UNDER,Validated,"Walker was contained, 19 carries for 3.3 ypc; ..."
2,Parkinson,Receptions,OVER,Stafford trusts Parkinson as his 2nd read; Dav...,~68%,"Market line reasonable, slight edge for OVER",OVER 2.5,2026-01-23 02:25,OVER 3,2026-01-24 AM,Volume will increase due to coverage,Supported by matchup + Stafford trust,3,OVER,Validated,Achieved line and produced efficiency over vol...
3,Blake Corum,Receiving Yards,OVER,Seahawks allow RB receiving yards with their s...,~57%,Market underestimates RB receiving usage; vola...,OVER 0.5,2026-01-23 02:28,OVER 1,2026-01-24 AM,Favorable for over 0.5; high variance remains,Supported by scheme and RB usage,3,OVER,Validated,Capitalized on defensive shell; linebacker/cor...

> **Note:** A prop may lose while the underlying thesis remains valid.  
> Result reflects the line; Thesis Validation reflects decision quality.

In [112]:
# Step 3: Display Table
from tabulate import tabulate

def display_table():
    print(tabulate(df, headers='keys', tablefmt='grid'))

display_table()

+----+-------------+-----------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+-----------------------------------------------------------------+-----------------+----------------------+--------------------------+---------------------+-----------------------------------------------+---------------------------------------+--------------+----------+---------------------+---------------------------------------------------------------------------------------------------------+
|    | Player      | Prop            | Type   | Pregame Hypothesis                                                                                                                                       | Confidence   | Market Alignment / Notes                                        | Baseline Prop   | Baseline Timestamp   | Current Prop             | Current Timestamp   | Adjusted Value                                | Pregame Thesis Status                 |   Final Stat | Result   | Thesis Validation   | Postgame Notes                                                                                          |
+====+=============+=================+========+==========================================================================================================================================================+==============+=================================================================+=================+======================+==========================+=====================+===============================================+=======================================+==============+==========+=====================+=========================================================================================================+
|  0 | Barner      | Receiving Yards | OVER   | Barner exceeds with playaction passing where Rams allow tight ends to hit explosive yards.                                                               | ~66%         | Market underestimates slot usage; early-week data supports OVER | OVER 28.5       | 2026-01-23 02:20     | OVER 30 (improved value) | 2026-01-24 AM       | More favorable to OVER 30                     | Supported by market                   |           13 | UNDER    | Invalidated         | Ball was spread evenly, given short routes, not game focus.                                             |
+----+-------------+-----------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+-----------------------------------------------------------------+-----------------+----------------------+--------------------------+---------------------+-----------------------------------------------+---------------------------------------+--------------+----------+---------------------+---------------------------------------------------------------------------------------------------------+
|  1 | Walker      | Rushing Yards   | UNDER  | Rams will collapse the pocket and apply extra measures to contain him; Seahawks won’t establish their run game due to game script and Charbonnet injury. | ~61%         | Market may overvalue workload; Rams rush D strong               | UNDER 85.5      | 2026-01-23 02:22     | UNDER 85.5               | 2026-01-24 AM       | Trend supports UNDER due to game script       | Strongly supported by thesis          |           62 | UNDER    | Validated           | Walker was contained, 19 carries for 3.3 ypc; game script had Seahawks leading, limiting effectiveness. |
+----+-------------+-----------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+-----------------------------------------------------------------+-----------------+----------------------+--------------------------+---------------------+-----------------------------------------------+---------------------------------------+--------------+----------+---------------------+---------------------------------------------------------------------------------------------------------+
|  2 | Parkinson   | Receptions      | OVER   | Stafford trusts Parkinson as his 2nd read; Davante Adams draws coverage, giving Parkinson volume and influence in the game.                              | ~68%         | Market line reasonable, slight edge for OVER                    | OVER 2.5        | 2026-01-23 02:25     | OVER 3                   | 2026-01-24 AM       | Volume will increase due to coverage          | Supported by matchup + Stafford trust |            3 | OVER     | Validated           | Achieved line and produced efficiency over volume.                                                      |
+----+-------------+-----------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+-----------------------------------------------------------------+-----------------+----------------------+--------------------------+---------------------+-----------------------------------------------+---------------------------------------+--------------+----------+---------------------+---------------------------------------------------------------------------------------------------------+
|  3 | Blake Corum | Receiving Yards | OVER   | Seahawks allow RB receiving yards with their shell defense; Corum should exploit checkdowns and screens, complementing Parkinson’s receptions.           | ~57%         | Market underestimates RB receiving usage; volatility remains    | OVER 0.5        | 2026-01-23 02:28     | OVER 1                   | 2026-01-24 AM       | Favorable for over 0.5; high variance remains | Supported by scheme and RB usage      |            3 | OVER     | Validated           | Capitalized on defensive shell; linebacker/corners dropped back as expected, beating line.              |
+----+-------------+-----------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+-----------------------------------------------------------------+-----------------+----------------------+--------------------------+---------------------+-----------------------------------------------+---------------------------------------+--------------+----------+---------------------+---------------------------------------------------------------------------------------------------------+

This table captures the full lifecycle of each prop:
- Baseline market line
- Pregame thesis and confidence
- Market alignment or disagreement
- Final stat and result
- Postgame thesis validation

In [113]:
# Step 4: Adjustment Function
def update_adjustment(player, new_value, reason, prop=None):
    """Update Adjusted Value and pregame rationale for a player or specific prop"""
    mask = df['Player'] == player
    if prop:
        mask &= df['Prop'] == prop
    df.loc[mask, 'Adjusted Value'] = new_value
    df.loc[mask, 'Postgame Notes'] = df.loc[mask, 'Postgame Notes'].fillna('') + " | " + reason
    df.loc[mask, 'Current Timestamp'] = datetime.now().strftime("%Y-%m-%d %H:%M")

In [114]:
# Step 5: Record Final Stats Function
def record_final_stats(player, final_stat, prop=None):
    """Record final outcome and calculate Result / Thesis Validation"""
    if prop:
        mask = (df['Player'] == player) & (df['Prop'] == prop)
    else:
        mask = (df['Player'] == player)
    df.loc[mask, 'Final Stat'] = final_stat
    df.loc[mask, 'Result'] = "OVER" if final_stat > float(str(df.loc[mask, 'Baseline Prop'].values[0]).split()[1]) else "UNDER"
    # Thesis validation placeholder: compare Result to expected prop type
    df.loc[mask, 'Thesis Validation'] = "Correct" if df.loc[mask, 'Result'].values[0] == df.loc[mask, 'Type'].values[0] else "Wrong"

In [115]:
# Step 6: Final Picks Summary
print("FINAL PICKS SUMMARY")
print("-" * 80)

for _, row in df.iterrows():
    lean = row['Type']
    adjusted = row['Adjusted Value'] if row['Adjusted Value'] else row['Baseline Prop']
    confidence = row['Confidence'] if row['Confidence'] else "N/A"
    final_stat = row['Final Stat'] if row['Final Stat'] else "N/A"
    result = row['Result'] if row['Result'] else "N/A"
    thesis_val = row['Thesis Validation'] if row['Thesis Validation'] else "N/A"
    
    print(
        f"{row['Player']} — {row['Prop']}: "
        f"{lean} (Adjusted: {adjusted}, Confidence: {confidence}) | "
        f"Final Stat: {final_stat} | Result: {result} | Thesis Validation: {thesis_val}"
    )

FINAL PICKS SUMMARY
--------------------------------------------------------------------------------
Barner — Receiving Yards: OVER (Adjusted: More favorable to OVER 30, Confidence: ~66%) | Final Stat: 13 | Result: UNDER | Thesis Validation: Invalidated
Walker — Rushing Yards: UNDER (Adjusted: Trend supports UNDER due to game script, Confidence: ~61%) | Final Stat: 62 | Result: UNDER | Thesis Validation: Validated
Parkinson — Receptions: OVER (Adjusted: Volume will increase due to coverage, Confidence: ~68%) | Final Stat: 3 | Result: OVER | Thesis Validation: Validated
Blake Corum — Receiving Yards: OVER (Adjusted: Favorable for over 0.5; high variance remains, Confidence: ~57%) | Final Stat: 3 | Result: OVER | Thesis Validation: Validated

# Postgame Analysis

**Key Takeaways:**

Postgame Summary & Lessons Learned

Result Summary:
- 3 of 4 props hit
- 2 props favored players on the losing team

Key Insight:
Even with favorable game script, Walker failed to reach efficiency thresholds,
validating the UNDER despite volume.


Misses were driven by:
- Unexpected target distribution
- Role-based usage rather than inefficiency

This reinforces the importance of distinguishing between:
"Wrong outcome" vs "Wrong thesis"

This notebook places greater emphasis on separating result accuracy
from thesis correctness, building on lessons from the Bears vs Rams analysis.

### Final Reflection

This slate hit 3 of 4 props despite two selections favoring the losing team.
Market assumptions typically penalize players on trailing teams, yet matchup
and role-based analysis allowed these props to outperform expectation.

This reinforces the importance of separating team outcome from player usage.

In [116]:
# Step 7: Trend & Accuracy Summary

# Total number of props
total_props = len(df)

# Number of correct hits
correct_hits = df['Thesis Validation'].value_counts().get('Validated', 0)

# Hit percentage
hit_percentage = round((correct_hits / total_props) * 100, 1)

# Number of over and under outcomes
over_hits = len(df[(df['Result'] == 'OVER') & (df['Thesis Validation'] == 'Validated')])
under_hits = len(df[(df['Result'] == 'UNDER') & (df['Thesis Validation'] == 'Validated')])

print("Postgame Evaluation & Takeaways")
print("-" * 60)
print(f"Total Props: {total_props}")
print(f"Correct Hits: {correct_hits}")
print(f"Hit %: {hit_percentage}%")
print(f"OVER Props Correct: {over_hits}")
print(f"UNDER Props Correct: {under_hits}")
print("\nProps Hit 3/4 this week despite two props favoring the losing team — strong predictive performance based on volume and matchup analysis.")

Postgame Evaluation & Takeaways
------------------------------------------------------------
Total Props: 4
Correct Hits: 3
Hit %: 75.0%
OVER Props Correct: 2
UNDER Props Correct: 1

Props Hit 3/4 this week despite two props favoring the losing team — strong predictive performance based on volume and matchup analysis.

## Project Reflection & Goal Alignment

This notebook represents a deliberate refinement from the Bears vs Rams project, prioritizing **efficiency, clarity, and decision-quality evaluation** over exhaustive explanation.

### Key Improvements From Prior Project
- **Reduced formatting and redundancy** — reused framework without re-explaining each step.
- **More efficient structure** — fewer cells and cleaner markdown for readability while preserving analytical rigor.
- **Clearer separation of outcome vs logic** — results are evaluated independently from thesis validity, reinforcing process integrity over result chasing.
- **Stronger postgame interpretation** — emphasis on *why* a prop succeeded or failed rather than restating the final stat.

### Analytical Focus & Insights
- Challenged the market assumption that **player props on losing teams are less likely to hit**.
- Evaluated whether **role-based usage, matchup context, and scheme alignment** could still support profitable props despite adverse game scripts.
- Observed that **3 of 4 props hit**, including **two selections favoring players on the losing team**.
- Efficiency-based props outperformed volume-based expectations.
- Rams adjusted predictably when trailing, creating value in secondary and role-specific usage.
- Defensive shell concepts supported RB receiving and short-area targets.

### Weather & Environmental Impact
- Unlike the Bears vs Rams matchup, this game occurred in a more neutral field environment.
- Snow and adverse conditions materially affected player outcomes in prior projects.
- This matchup highlights how **environmental factors influence whether players meet stat lines**, even when underlying logic remains sound.

### Process Validation
- One prop “failed,” but the underlying reasoning aligned with game flow, usage, and defensive response.
- Reinforces the core objective: **evaluate decision quality, not just correctness**.
- Logic held across different game scripts, conditions, and opponent adjustments.

### Closing Takeaway
- Demonstrates progression from framework construction to **analytical refinement**.
- Reducing noise, sharpening observations, and testing assumptions against tougher conditions improved discipline, confidence, and explanatory power.
- The 3/4 hit rate — particularly under challenging market assumptions — shows that the process remains **sound, repeatable, and transferable** to future high-leverage slates.

### Next Iteration
Future application of this framework will focus on high-stakes games like the Super Bowl, testing whether role-based, matchup-aware, and environmental logic holds under maximum pressure and across unique matchups.