# Broncos vs Patriots — Player Prop Analysis

This notebook logs pregame player prop assumptions, market movement,
and postgame outcomes for evaluation.

All baseline entries are frozen prior to kickoff.

## Objectives

- Record baseline player prop lines with timestamps
- Track pregame market movement and adjustments
- Preserve reasoning without hindsight bias
- Evaluate outcomes postgame
- Measure accuracy of predictions vs final stats

## Methodology

This notebook separates:
1. **Baseline assumptions** – lines and probabilities before market moves
2. **Pregame adjustments** – updated market trends, value shifts, and thesis support
3. **Postgame outcomes** – final stats, calculated lean, thesis validation, and notes

**No baseline edits are allowed once the week’s pregame snapshot is frozen.**

In [11]:
import pandas as pd
from datetime import datetime

# Define all columns including placeholders for postgame data
columns = [
    "Player",
    "Prop",
    "Type",
    "Expected Outcome",
    "Confidence",
    "Market Alignment / Notes",
    "Baseline Prop",
    "Baseline Timestamp",
    "Current Prop",
    "Current Timestamp",
    "Adjusted Value",
    "Pregame Thesis Status",
    "Final Stat",
    "Result",
    "Thesis Validation",
    "Postgame Notes"
]

# Create empty DataFrame
df = pd.DataFrame(columns=columns)
df

Empty DataFrame
Columns: [Player, Prop, Type, Expected Outcome, Confidence, Market Alignment / Notes, Baseline Prop, Baseline Timestamp, Current Prop, Current Timestamp, Adjusted Value, Pregame Thesis Status, Final Stat, Result, Thesis Validation, Postgame Notes]
Index: []

In [12]:
# Step 4: Pre-game prop entries
data = [
    {
        "Player": "Drake Maye",
        "Prop": "Passing Touchdowns",
        "Type": "OVER",
        "Expected Outcome": "Lean OVER 1.5–2 TDs; Broncos red-zone pressure may allow 2",
        "Confidence": "~68%",
        "Market Alignment / Notes": "Market initially favored UNDER 1.5",
        "Baseline Prop": "OVER 1.5",
        "Baseline Timestamp": "2026-01-23 02:00",
        "Current Prop": "OVER 1.5 (improved value)",
        "Current Timestamp": "2026-01-24 AM",
        "Adjusted Value": "More favorable to OVER",
        "Pregame Thesis Status": "Supported by market",
        "Final Stat": None,
        "Result": None,
        "Thesis Validation": None,
        "Postgame Notes": None
    },
    {
        "Player": "Hunter Henry",
        "Prop": "Anytime Touchdown",
        "Type": "OVER",
        "Expected Outcome": "Soft red-zone coverage → scoring opportunity; high variance prop",
        "Confidence": "~55% (high variance)",
        "Market Alignment / Notes": "TD odds shortened since baseline",
        "Baseline Prop": "TD YES",
        "Baseline Timestamp": "2026-01-23 02:05",
        "Current Prop": "TD YES (more favored)",
        "Current Timestamp": "2026-01-24 AM",
        "Adjusted Value": "Market moving toward YES",
        "Pregame Thesis Status": "Supported by market",
        "Final Stat": None,
        "Result": None,
        "Thesis Validation": None,
        "Postgame Notes": None
    },
    {
        "Player": "Broncos RB (Harvey)",
        "Prop": "Rushing Attempts",
        "Type": "OVER",
        "Expected Outcome": "Increased role due to Dobbins injury; game expected close",
        "Confidence": "~63%",
        "Market Alignment / Notes": "Market mixed early",
        "Baseline Prop": "OVER 12.0",
        "Baseline Timestamp": "2026-01-23 02:10",
        "Current Prop": "OVER 12.5",
        "Current Timestamp": "2026-01-24 AM",
        "Adjusted Value": "Line increased",
        "Pregame Thesis Status": "Neutral",
        "Final Stat": None,
        "Result": None,
        "Thesis Validation": None,
        "Postgame Notes": None
    },
    {
        "Player": "Game",
        "Prop": "Total Points",
        "Type": "UNDER",
        "Expected Outcome": "Defensive, clock-managed game expected",
        "Confidence": "~60%",
        "Market Alignment / Notes": "Total nudged upward",
        "Baseline Prop": "UNDER 42.5",
        "Baseline Timestamp": "2026-01-23 02:15",
        "Current Prop": "UNDER 43.0",
        "Current Timestamp": "2026-01-24 AM",
        "Adjusted Value": "Market moved against UNDER",
        "Pregame Thesis Status": "Challenged by market",
        "Final Stat": None,
        "Result": None,
        "Thesis Validation": None,
        "Postgame Notes": None
    }
]

# Insert into DataFrame
df = pd.DataFrame(data)
df

,Player,Prop,Type,Expected Outcome,Confidence,Market Alignment / Notes,Baseline Prop,Baseline Timestamp,Current Prop,Current Timestamp,Adjusted Value,Pregame Thesis Status,Final Stat,Result,Thesis Validation,Postgame Notes
0,Drake Maye,Passing Touchdowns,OVER,Lean OVER 1.5–2 TDs; Broncos red-zone pressure...,~68%,Market initially favored UNDER 1.5,OVER 1.5,2026-01-23 02:00,OVER 1.5 (improved value),2026-01-24 AM,More favorable to OVER,Supported by market,None,None,None,None
1,Hunter Henry,Anytime Touchdown,OVER,Soft red-zone coverage → scoring opportunity; ...,~55% (high variance),TD odds shortened since baseline,TD YES,2026-01-23 02:05,TD YES (more favored),2026-01-24 AM,Market moving toward YES,Supported by market,None,None,None,None
2,Broncos RB (Harvey),Rushing Attempts,OVER,Increased role due to Dobbins injury; game exp...,~63%,Market mixed early,OVER 12.0,2026-01-23 02:10,OVER 12.5,2026-01-24 AM,Line increased,Neutral,None,None,None,None
3,Game,Total Points,UNDER,"Defensive, clock-managed game expected",~60%,Total nudged upward,UNDER 42.5,2026-01-23 02:15,UNDER 43.0,2026-01-24 AM,Market moved against UNDER,Challenged by market,None,None,None,None

In [13]:
from tabulate import tabulate

def display_table():
    print(tabulate(df, headers='keys', tablefmt='grid'))

# Display current pregame props
display_table()

+----+---------------------+--------------------+--------+------------------------------------------------------------------+----------------------+------------------------------------+-----------------+----------------------+---------------------------+---------------------+----------------------------+-------------------------+--------------+----------+---------------------+------------------+
|    | Player              | Prop               | Type   | Expected Outcome                                                 | Confidence           | Market Alignment / Notes           | Baseline Prop   | Baseline Timestamp   | Current Prop              | Current Timestamp   | Adjusted Value             | Pregame Thesis Status   | Final Stat   | Result   | Thesis Validation   | Postgame Notes   |
+====+=====================+====================+========+==================================================================+======================+====================================+=================+======================+===========================+=====================+============================+=========================+==============+==========+=====================+==================+
|  0 | Drake Maye          | Passing Touchdowns | OVER   | Lean OVER 1.5–2 TDs; Broncos red-zone pressure may allow 2       | ~68%                 | Market initially favored UNDER 1.5 | OVER 1.5        | 2026-01-23 02:00     | OVER 1.5 (improved value) | 2026-01-24 AM       | More favorable to OVER     | Supported by market     |              |          |                     |                  |
+----+---------------------+--------------------+--------+------------------------------------------------------------------+----------------------+------------------------------------+-----------------+----------------------+---------------------------+---------------------+----------------------------+-------------------------+--------------+----------+---------------------+------------------+
|  1 | Hunter Henry        | Anytime Touchdown  | OVER   | Soft red-zone coverage → scoring opportunity; high variance prop | ~55% (high variance) | TD odds shortened since baseline   | TD YES          | 2026-01-23 02:05     | TD YES (more favored)     | 2026-01-24 AM       | Market moving toward YES   | Supported by market     |              |          |                     |                  |
+----+---------------------+--------------------+--------+------------------------------------------------------------------+----------------------+------------------------------------+-----------------+----------------------+---------------------------+---------------------+----------------------------+-------------------------+--------------+----------+---------------------+------------------+
|  2 | Broncos RB (Harvey) | Rushing Attempts   | OVER   | Increased role due to Dobbins injury; game expected close        | ~63%                 | Market mixed early                 | OVER 12.0       | 2026-01-23 02:10     | OVER 12.5                 | 2026-01-24 AM       | Line increased             | Neutral                 |              |          |                     |                  |
+----+---------------------+--------------------+--------+------------------------------------------------------------------+----------------------+------------------------------------+-----------------+----------------------+---------------------------+---------------------+----------------------------+-------------------------+--------------+----------+---------------------+------------------+
|  3 | Game                | Total Points       | UNDER  | Defensive, clock-managed game expected                           | ~60%                 | Total nudged upward                | UNDER 42.5      | 2026-01-23 02:15     | UNDER 43.0                | 2026-01-24 AM       | Market moved against UNDER | Challenged by market    |              |          |                     |                  |
+----+---------------------+--------------------+--------+------------------------------------------------------------------+----------------------+------------------------------------+-----------------+----------------------+---------------------------+---------------------+----------------------------+-------------------------+--------------+----------+---------------------+------------------+

In [14]:
def update_adjustment(player, new_value, reason, prop=None):
    """Update Adjusted Value and pregame rationale for a player or specific prop"""
    mask = df['Player'] == player
    if prop:
        mask &= df['Prop'] == prop
    df.loc[mask, 'Adjusted Value'] = new_value
    df.loc[mask, 'Postgame Notes'] = df.loc[mask, 'Postgame Notes'].fillna('') + " | " + reason
    df.loc[mask, 'Current Timestamp'] = datetime.now().strftime("%Y-%m-%d %H:%M")

def record_outcome(player, final_stat, prop=None):
    if prop:
        mask = (df['Player'] == player) & (df['Prop'] == prop)
    else:
        mask = (df['Player'] == player)
    df.loc[mask, 'Final Stat'] = final_stat
    df.loc[mask, 'Result'] = "OVER" if final_stat > df.loc[mask, 'Baseline Prop'].values[0] else "UNDER"
    # Thesis validation placeholder
    df.loc[mask, 'Thesis Validation'] = df.loc[mask, 'Result']  # initially, can compare with Expected Outcome

In [15]:
# ================================
# Step 7: Final Picks Summary
# ================================

print("FINAL PICKS SUMMARY")
print("-" * 60)

for _, row in df.iterrows():
    lean = row['Type']  # OVER or UNDER
    adjusted = row['Adjusted Value'] if row['Adjusted Value'] else row['Baseline Prop']
    confidence = row['Confidence'] if row['Confidence'] else "N/A"
    print(
        f"{row['Player']} — {row['Prop']}: "
        f"{lean} (Adjusted: {adjusted}, Confidence: {confidence})"
    )

FINAL PICKS SUMMARY
------------------------------------------------------------
Drake Maye — Passing Touchdowns: OVER (Adjusted: More favorable to OVER, Confidence: ~68%)
Hunter Henry — Anytime Touchdown: OVER (Adjusted: Market moving toward YES, Confidence: ~55% (high variance))
Broncos RB (Harvey) — Rushing Attempts: OVER (Adjusted: Line increased, Confidence: ~63%)
Game — Total Points: UNDER (Adjusted: Market moved against UNDER, Confidence: ~60%)